### ISSUE TITLE
documentation question: what does "withIcon" stand for?

### ISSUE THREAD

**Issue by yofu1234** [GrenderG/Toasty#16]
`Toasty.custom(yourContext, "I'm a custom Toast", yourIconDrawable, textColor, tintColor, duration, withIcon, true).show();
`

what does "withIcon" stand for?
Also is their a way to have your own custom colors while using Toasty's default icons like the checkmark?

**Comment by GrenderG** [comment]
> what does "withIcon" stand for?

`withIcon` is a boolean parameter to set if that Toast should show the passed icon or not.

> Also is there a way to have your own custom colors while using Toasty's default icons like the checkmark?

You can't do that directly, but since Toasty's icons are in the library you can access them by typing their [corresponding ids](https://github.com/GrenderG/Toasty/tree/master/toasty/src/main/res/drawable-hdpi).
