### ISSUE TITLE
Apply Radius to toast message

### ISSUE THREAD

**Issue by Bennith** [GrenderG/Toasty#4]
Hi @GrenderG 

Great plugin you have here, just request if possible to have or assign the toast radius (so corners are not so rounded).

Programmatically 

Toasty.custom(yourContext, "I'm a custom Toast", yourIconDrawable, textColor, tintColor, duration, withIcon, cornerRadius, true).show();

**Comment by GrenderG** [comment]
Hello @Bennith and thanks for your suggestions.

Unfortunately this library aims to be an enhancement of the **original** Toast, in fact, I'm using the [original Toast's `NinePatchDrawable` image](https://github.com/GrenderG/Toasty/blob/master/toasty/src/main/res/drawable-hdpi/toast_frame.9.png) in order to create the layout. 

Because of that, I'm not planning to change the Toast's frame. Sorry for any inconveniences. :disappointed:

**Comment by Bennith** [comment]
Ok fair enough, thanks for the response.
