### ISSUE TITLE
Possibility to cancel toast to show new one

### ISSUE THREAD

**Issue by koenschauwaert** [GrenderG/Toasty#79]
As the title says: I am looking for a possibility to cancel a toast to make room for a new one. Sometimes toasts are shown on top of each other and when at first an error is shown with a succes-toast on top, it confuses the user.

**Comment by jpvs0101** [comment]
Yes, that would be awesome, also instead of cancel, why don't implement
stacked like one above another so that the user don't miss any!
On 23-Jul-2018 3:28 pm, "Koen Schauwaert" <notifications@github.com> wrote:

As the title says: I am looking for a possibility to cancel a toast to make
room for a new one. Sometimes toasts are shown on top of each other and
when at first an error is shown with a succes-toast on top, it confuses the
user.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/GrenderG/Toasty/issues/79>, or mute the thread

**Comment by GrenderG** [comment]
Hello, **Toasty** is fully based on vanilla Toast (in fact, it just customizes them), so the behavior is handled by `Toast` objects.

You can call the [cancel method](https://developer.android.com/reference/android/widget/Toast#cancel()) on the `Toast` object which returns each Toasty method to cancel them.

**Comment by koenschauwaert** [comment]
@GrenderG I'll try that first thing tomorrow. I'll get back on this if I get it working. If so, maybe don't delete this issue, but just mark it as 'closed' or 'fixed' so other people looking for this know how it's done.

**Comment by GrenderG** [comment]
Don't worry, I just close them. :stuck_out_tongue:

Glad it worked!
